# After changing this file, check it on:
#   http://lint.travis-ci.org/

language: python
python:
 - 3.3
sudo: false
# Remove pip; it apparently http://gramps.1791082.n4.nabble.com/Why-is-Travis-CI-unable-to-import-coverage-and-pyicu-tp4676124p4676125.html
# "Currently, all of the items installed with pip in .travis.yml are not used,
# because nosetests3 uses the built-in Python3 which has access to the system installed packages (gtk, cairo, etc)."
# cache: pip
addons:
  apt:
    packages:
    - gir1.2-pango-1.0
    - gir1.2-gtk-3.0
    - xdg-utils
    - librsvg2-common
    - libglib2.0-dev
    - intltool
    # - python3-gobject Provided by python3-gi
    - python3-gi
    - python3-cairo
    - python3-gi-cairo
    - python3-bsddb3
    - python3-dev
    - python3-nose
    - python3-mock
    - python-pyicu
    - python3-nose

before_install:
# - pip install --upgrade pip
 - pip install --upgrade codecov

install:
# - travis_retry pip install --upgrade pillow
# - travis_retry pip install pyicu==1.8
 - wget https://pypi.python.org/packages/53/fe/9e0fbdbca15c2c1253379c3a694f4315a420555e7874445b06edeaeacaea/coverage-4.2.tar.gz
 - tar -xzvf coverage-4.2.tar.gz
 - pushd coverage-4.2 && python setup.py install && popd

 # - cd $TRAVIS_BUILD_DIR
 # $TRAVIS_BUILD_DIR is set to the location of the cloned repository:
 # for example: /home/travis/build/gramps-project/gramps
 - git clone -b master https://github.com/srossross/meta
 - python setup.py build

before_script:
#    - sudo Xvfb :99 -ac &
#    - export DISPLAY=:99
 - mkdir -p ~/.gramps/grampsdb/
 - which python
 - which nosetests3
 - which nosetests
 - which coverage
 - ls /home/travis/virtualenv/python3.3.5/bin
 - ls /usr/lib/python3/dist-packages
 - ls /home/travis/virtualenv/python3.3.5/lib/python3.3/site-packages
 - ls /home/travis/build
 - ls /usr/bin

script:
 # --exclude=TestUser because of older version of mock
 #                    without configure_mock
 - export PYTHONHOME=`python -c "import sys;print(':'.join(sys.path[1:]))"`:/usr/lib/python3/dist-packages
 - echo $PYTHONHOME
# - export PYTHONHOME=/home/travis/virtualenv/python3.3.5/lib:/opt/python/3.3.5/lib/python3.3
# - python -c "import sys;print(sys.path)" 
 - PYTHONPATH=meta:/home/travis/virtualenv/python3.3.5/lib/python3.3/site-packages GRAMPS_RESOURCES=. nosetests --nologcapture --with-coverage --cover-package=gramps --exclude=TestcaseGenerator --exclude=vcard --exclude=merge_ref_test  --exclude=user_test gramps
 - if git --no-pager grep --color -n --full-name '[ 	]$' -- \*.py; then
     echo "ERROR - Trailing whitespace found in source file(s)";
     exit 1;
   fi

after_success:
 - codecov

