# After changing this file, check it on:
#   http://lint.travis-ci.org/

sudo: required
dist: trusty
language: python
python:
 - 3.3 # This is irrelevant, because the virtualenv is not used at all
# Remove pip; it apparently http://gramps.1791082.n4.nabble.com/Why-is-Travis-CI-unable-to-import-coverage-and-pyicu-tp4676124p4676125.html
# "Currently, all of the items installed with pip in .travis.yml are not used,
# because nosetests3 uses the built-in Python3 which has access to the system installed packages (gtk, cairo, etc)."
# cache: pip
addons:
  apt:
    packages:
    - gir1.2-pango-1.0
    - gir1.2-gtk-3.0
    - xdg-utils
    - librsvg2-common
    - libglib2.0-dev
    - intltool
    # - python3-gobject Provided by python3-gi
    - python3-gi
    - python3-cairo
    - python3-gi-cairo
    - python3-bsddb3
    - python3-dev
    - python3-nose
    - python3-mock
    - python3-pyicu
    - python3-coverage

before_install:
# - pip install --upgrade pip
 - pip install --upgrade codecov

install:
# - travis_retry pip install --upgrade pillow
# - travis_retry pip install pyicu==1.8
# Install coverage into /home/travis/virtualenv/python3.3.6/bin and /home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages
# - wget https://pypi.python.org/packages/53/fe/9e0fbdbca15c2c1253379c3a694f4315a420555e7874445b06edeaeacaea/coverage-4.2.tar.gz
# - tar -xzvf coverage-4.2.tar.gz
# - pushd coverage-4.2 && python setup.py install && popd

 # - cd $TRAVIS_BUILD_DIR
 # $TRAVIS_BUILD_DIR is set to the location of the cloned repository:
 # for example: /home/travis/build/gramps-project/gramps
# Download Sean Ross-Ross's Pure Python module containing a framework to manipulate and analyze python ast’s and bytecode
 - git clone -b master https://github.com/srossross/meta
# Build Gramps package
 - python setup.py build

before_script:
#    - sudo Xvfb :99 -ac &
#    - export DISPLAY=:99
# Create the Gramps database directory.
 - mkdir -p ~/.gramps/grampsdb/
 - which python
 - which nosetests3
 - which nosetests
 - ls /home/travis/virtualenv/python3.3.6/bin
 - ls -R /usr/lib/python3
 - ls /home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages
 - ls /home/travis/build
 - ls /usr/bin
# set PYTHONPATH so the directly installed modules (meta and coverage) are picked up from the virtualenv
# - export PYTHONPATH=meta:/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages
# set PYTHONPATH so the directly installed modules (meta) is picked up from /home/travis/build/gramps-project/gramps/meta
 - export PYTHONPATH=meta
# set module exclusions. --exclude=TestUser because of older version of mock without configure_mock
 - export EXCLUDE="--exclude=TestcaseGenerator --exclude=vcard --exclude=merge_ref_test --exclude=user_test --exclude=constfunc_test.py"
# set GRAMPS_RESOURCES something to do with database?
 - export GRAMPS_RESOURCES=.

script:
# - PYTHONPATH=meta GRAMPS_RESOURCES=. nosetests --nologcapture  --exclude=TestcaseGenerator --exclude=vcard --exclude=merge_ref_test  --exclude=user_test constfunc_test.py
# This uses system components and the apt-get installed packages
# - PYTHONPATH=meta:/usr/lib/python3/dist-packages:/home/travis/virtualenv/python3.3.5/lib/python3.3/site-packages GRAMPS_RESOURCES=. nosetests3 --nologcapture --exclude=TestcaseGenerator --exclude=vcard --exclude=merge_ref_test  --exclude=user_test gramps
# This uses system components and the apt-get installed packages, but fails because it uses Python 3.2 and coverage needs Python 3.4
# - PYTHONPATH=meta:/usr/lib/python3/dist-packages:/home/travis/virtualenv/python3.3.5/lib/python3.3/site-packages GRAMPS_RESOURCES=. nosetests3 --nologcapture --with-coverage --cover-package=gramps --exclude=TestcaseGenerator --exclude=vcard --exclude=merge_ref_test  --exclude=user_test gramps
# This is an attempt to use the vuirtual environment nosetests, python, coverage and python standard packages with the apt-get installed packages. 
 - /usr/bin/python3 -c "import sys;print(sys.path[1:])"
# - export VIRTPYTHONHOME=`python -c "import sys;print(':'.join(sys.path[1:]))"`
# - echo $VIRTPYTHONHOME
# - export SYSPYTHONHOME=/usr/lib/python3/dist-packages:/home/travis/virtualenv/python3.3.5/lib/python3.3/site-packages:/usr/lib/python3.2:/usr/lib/python3.2/plat-linux2:/usr/lib/python3.2/lib-dynload:/usr/local/lib/python3.2/dist-packages
# - echo $SYSPYTHONHOME
# - export PYTHONHOME=$VIRTPYTHONHOME:$SYSPYTHONHOME
# - echo $PYTHONHOME
# - export PYTHONHOME=/home/travis/build/gramps-project/gramps/gramps:/home/travis/build/gramps-project/gramps:/usr/bin:/home/travis/build/gramps-project/gramps/meta:/usr/lib/python3/dist-packages:/home/travis/virtualenv/python3.3.5/lib/python3.3/site-packages:/usr/lib/python3.2:/usr/lib/python3.2/plat-linux2:/usr/lib/python3.2/lib-dynload:/usr/local/lib/python3.2/dist-packages
# - export PYTHONHOME=/home/travis/virtualenv/python3.3.5/lib:/opt/python/3.3.5/lib/python3.3
# - python -c "import sys;print(sys.path)" 
# Ignore the virtualenv entirely. Use nosetests3, python3 (3.4.0) and coverage from /usr/bin. Use libraries from /usr/lib/python3.4 and /usr/local/lib/python3.4/dist-packages
 - nosetests3 --nologcapture --with-coverage --cover-package=gramps $EXCLUDE gramps
 - if git --no-pager grep --color -n --full-name '[ 	]$' -- \*.py; then
     echo "ERROR - Trailing whitespace found in source file(s)";
     exit 1;
   fi

after_success:
 - pwd
 - cd
 - pwd
 - find /home/travis/build/gramps-project/gramps -type f -name '*.gcno' ls
 - which codecov
 - codecov
 - find /home/travis/build/gramps-project/gramps -type f -name '*.xml' ls


